import { StyleSheet } from 'react-native';

export const ACCENT_COLOR = 'hsl(196, 100%, 44%)';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#05070a' },
  screen: { flex: 1, backgroundColor: '#05070a' },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#05070a' },
  onboardingCard: { flex: 1, justifyContent: 'center', padding: 28, gap: 16 },
  eyebrow: { color: ACCENT_COLOR, fontSize: 13, fontWeight: '700', letterSpacing: 1.4, textTransform: 'uppercase' },
  title: { color: '#f6f8fb', fontSize: 30, fontWeight: '800' },
  body: { color: '#a8b0bf', fontSize: 16, lineHeight: 23 },
  muted: { color: '#788397', fontSize: 13, lineHeight: 19 },
  input: { backgroundColor: '#101722', borderColor: '#263244', borderRadius: 12, borderWidth: 1, color: '#f6f8fb', fontSize: 16, padding: 14 },
  primaryButton: { alignItems: 'center', backgroundColor: ACCENT_COLOR, borderRadius: 14, padding: 15 },
  primaryButtonText: { color: '#f6f8fb', fontSize: 16, fontWeight: '800' },
  secondaryButton: { borderColor: '#2f3b4d', borderRadius: 999, borderWidth: 1, paddingHorizontal: 16, paddingVertical: 9 },
  secondaryButtonText: { color: '#f6f8fb', fontWeight: '700' },
  webview: { flex: 1, backgroundColor: '#05070a' },
  header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 14 },
  listContent: { padding: 12, paddingBottom: 32 },
  updateLink: { backgroundColor: '#102631', borderColor: ACCENT_COLOR, borderRadius: 14, borderWidth: 1, marginBottom: 12, padding: 14 },
  updateLinkText: { color: '#8ee7ff', fontSize: 15, fontWeight: '800', textAlign: 'center' },
  appRow: { alignItems: 'center', backgroundColor: '#101722', borderRadius: 18, flexDirection: 'row', gap: 14, marginBottom: 10, padding: 14 },
  appIcon: { borderRadius: 12, height: 48, width: 48 },
  appIconFallback: { alignItems: 'center', backgroundColor: '#243145', borderRadius: 12, height: 48, justifyContent: 'center', width: 48 },
  appIconLetter: { color: '#f6f8fb', fontSize: 20, fontWeight: '800' },
  appText: { flex: 1 },
  appTitle: { color: '#f6f8fb', fontSize: 17, fontWeight: '700' },
  appPackage: { color: '#687080', fontSize: 12, marginTop: 3 },
  pin: { color: ACCENT_COLOR, fontSize: 12, fontWeight: '800', textTransform: 'uppercase' },
  scroll: { padding: 16, paddingBottom: 40 },
  section: { marginBottom: 22 },
  sectionTitle: { color: ACCENT_COLOR, fontSize: 13, fontWeight: '800', letterSpacing: 1, marginBottom: 8, textTransform: 'uppercase' },
  card: { backgroundColor: '#101722', borderColor: '#1e2a3b', borderRadius: 16, borderWidth: 1, marginBottom: 10, overflow: 'hidden' },
  row: { alignItems: 'center', borderBottomColor: '#1e2a3b', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 52, paddingHorizontal: 15, paddingVertical: 10 },
  rowText: { color: '#f6f8fb', flex: 1, fontSize: 15, fontWeight: '600' },
  rowValue: { color: '#8d99aa', fontSize: 14, marginLeft: 12, maxWidth: '55%', textAlign: 'right' },
  warning: { backgroundColor: '#302315', borderColor: '#8b5d20', borderRadius: 12, borderWidth: 1, marginBottom: 10, padding: 12 },
  warningText: { color: '#f0c47a', fontSize: 13, lineHeight: 19 },
  status: { color: '#7df2b0', fontSize: 14, fontWeight: '700' },
  error: { color: '#ff8c8c', fontSize: 13 },
  buttonRow: { flexDirection: 'row', gap: 10, marginTop: 8 },
  smallButton: { alignItems: 'center', backgroundColor: '#1d2b3d', borderRadius: 10, flex: 1, padding: 12 },
  smallButtonText: { color: '#dce6f4', fontSize: 13, fontWeight: '700' },
});
